# Generated by Django 5.2.1 on 2025-06-05 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='entry',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
