# Generated by Django 5.2.1 on 2025-06-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_rename_desc_task_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='entry_date',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_date',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('PERSONAL', 'Personal')], max_length=20),
        ),
    ]
