# Generated by Django 5.2.1 on 2025-06-05 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
