# Generated by Django 5.2.1 on 2025-06-05 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_alter_login_date_joined_alter_login_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='last_password_change',
        ),
    ]
