# Generated by Django 5.2.1 on 2025-06-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_rename_customer_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
