name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd ToDoList
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        cd ToDoList
        python manage.py migrate

    - name: Run tests
      run: |
        cd ToDoList
        python manage.py test
